apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: strong-mink-go 
  janus-idp.io/tekton: strong-mink-go
  backstage.io/kubernetes-id: strong-mink-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: strong-mink-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  